SET(SDL2TTF_SEARCH_PATHS
        ~/Library/Frameworks
        /Library/Frameworks
        /usr/local
        /usr
        /sw
        /opt/local
        /opt/csw
        /opt
        )

FIND_PATH(SDL2TTF_INCLUDE_DIR SDL_ttf.h
        HINTS
        $ENV{SDL2TTFDIR}
        PATH_SUFFIXES include/SDL2 include
        PATHS ${SDL2TTF_SEARCH_PATHS}
        )

FIND_LIBRARY(SDL2TTF_LIBRARY_TEMP
        NAMES SDL2_ttf
        HINTS
        $ENV{SDL2TTFDIR}
        PATH_SUFFIXES lib64 lib
        PATHS ${SDL2TTF_SEARCH_PATHS}
        )

IF(NOT SDL2TTF_BUILDING_LIBRARY)
    IF(NOT ${SDL2TTF_INCLUDE_DIR} MATCHES ".framework")
        FIND_LIBRARY(SDL2TTFMAIN_LIBRARY
                NAMES SDL2_ttf
                HINTS
                $ENV{SDL2TTFDIR}
                PATH_SUFFIXES lib64 lib
                PATHS ${SDL2TTF_SEARCH_PATHS}
                )
    ENDIF(NOT ${SDL2TTF_INCLUDE_DIR} MATCHES ".framework")
ENDIF(NOT SDL2TTF_BUILDING_LIBRARY)

IF(NOT APPLE)
    FIND_PACKAGE(Threads)
ENDIF(NOT APPLE)

IF(MINGW)
    SET(MINGW32_LIBRARY mingw32 CACHE STRING "mwindows for MinGW")
ENDIF(MINGW)

IF(SDL2TTF_LIBRARY_TEMP)
    IF(NOT SDL2TTF_BUILDING_LIBRARY)
        IF(SDL2TTFMAIN_LIBRARY)
            SET(SDL2TTF_LIBRARY_TEMP ${SDL2TTFMAIN_LIBRARY} ${SDL2TTF_LIBRARY_TEMP})
        ENDIF(SDL2TTFMAIN_LIBRARY)
    ENDIF(NOT SDL2TTF_BUILDING_LIBRARY)

    IF(APPLE)
        SET(SDL2TTF_LIBRARY_TEMP ${SDL2TTF_LIBRARY_TEMP} "-framework Cocoa")
    ENDIF(APPLE)

    IF(NOT APPLE)
        SET(SDL2TTF_LIBRARY_TEMP ${SDL2TTF_LIBRARY_TEMP} ${CMAKE_THREAD_LIBS_INIT})
    ENDIF(NOT APPLE)

    IF(MINGW)
        SET(SDL2TTF_LIBRARY_TEMP ${MINGW32_LIBRARY} ${SDL2TTF_LIBRARY_TEMP})
    ENDIF(MINGW)

    SET(SDL2TTF_LIBRARY ${SDL2TTF_LIBRARY_TEMP} CACHE STRING "Where the SDL2TTF Library can be found")
    SET(SDL2TTF_LIBRARY_TEMP "${SDL2TTF_LIBRARY_TEMP}" CACHE INTERNAL "")
ENDIF(SDL2TTF_LIBRARY_TEMP)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2TTF REQUIRED_VARS SDL2TTF_LIBRARY SDL2TTF_INCLUDE_DIR)